excersisesData = {
    "Squat": "https://www.youtube.com/shorts/MLoZuAkIyZI",
    "Deadlift": "https://www.youtube.com/shorts/vfKwjT5-86k",
    "Bench Press": "https://www.youtube.com/shorts/0cXAp6WhSj4",
    "Overhead Press": "https://www.youtube.com/shorts/BbpaHO_vVe4",
    "Barbell Row": "https://www.youtube.com/shorts/Nqh7q3zDCoQ",
    "Pull-Up": "https://www.youtube.com/shorts/WSLbL7hqP4k",
    "Chin-Up": "https://www.youtube.com/shorts/Oi3bW9nQmGI",
    "Leg Press": "https://www.youtube.com/shorts/LG2L25PkeYU",
    "Lunges": "https://www.youtube.com/shorts/LCWWq3Lx2Sk",
    "Bulgarian Split Squat": "https://www.youtube.com/shorts/uODWo4YqbT8",
    "Push-Up": "https://www.youtube.com/shorts/ba8tr1NzwXU",
    "Dips": "https://www.youtube.com/shorts/ci5tcFgIntI",
    "Plank": "https://www.youtube.com/shorts/2xc9W2bdsJs",
    "Side Plank": "https://www.youtube.com/watch?v=NXr4Fw8q60o",
    "lying Leg Raise": "https://www.youtube.com/shorts/-7YZe1ToQfc",
    "Hanging Leg Raise": "https://www.youtube.com/shorts/7DoFMV1Dnow",
    "Burpees": "https://www.youtube.com/watch?v=auBLPXO8Fww",
    "Barbell Curl": "https://www.youtube.com/watch?v=kwG2ipFRgfo",
    "Hammer Curl": "https://www.youtube.com/watch?v=TwD-YGVP4Bk",
    "Concentration Curl": "https://www.youtube.com/watch?v=0AUGkch3tzc",
    "Skull Crushers": "https://www.youtube.com/watch?v=S0fmDR60X-o",
    "Tricep Kickback": "https://www.youtube.com/shorts/F0hRXsCylig",
    "Close-Grip Bench Press": "https://www.youtube.com/shorts/VYC2QZEOIUI",
    "Seated Calf Raise": "https://www.youtube.com/shorts/pHm6LFuGGbs",
    "Leg Curl": "https://www.youtube.com/shorts/7PE3MlvGAts",
    "Leg Extension": "https://www.youtube.com/watch?v=ljO4jkwv8wQ",
    "Lat Pull-Down": "https://www.youtube.com/watch?v=XA4ZmYeFsW8",
    "Face Pull": "https://www.youtube.com/shorts/IUdME60uDeU",
    "T-Bar Row": "https://www.youtube.com/shorts/MIulz5576AY",
    "Dumbbell Fly": "https://www.youtube.com/watch?v=QENKPHhQVi4",
    "Dumbbell Press": "https://www.youtube.com/shorts/SidmT09GXz8",
    "Dumbbell Row": "https://www.youtube.com/watch?v=roCP6wCXPqo",
    "Dumbbell Lateral Raise": "https://www.youtube.com/shorts/JIhbYYA1Q90",
    "Front Raise": "https://www.youtube.com/shorts/yHx8wPv4RPo",
    "Shrugs": "https://www.youtube.com/shorts/8JYpwj1kGV4",
    "Upright Row": "https://www.youtube.com/watch?v=jaAV-rD45I0",
    "Romanian Deadlift": "https://www.youtube.com/watch?v=_oyxCn2iSjU",
    "Sumo Deadlift": "https://www.youtube.com/shorts/e7oLkRlT2CQ",
    "Hack Squat": "https://www.youtube.com/watch?v=0tn5K9NlCfo",
    "Goblet Squat": "https://www.youtube.com/watch?v=CkFzgR55gho",
    "Kettlebell Swing": "https://www.youtube.com/shorts/aSYap2yhW8s",
    "Kettlebell Deadlift": "https://www.youtube.com/watch?v=eFkeIXvhSFs",
    "Incline Barbell Bench Press": "https://www.youtube.com/watch?v=SrqOu55lrYU",
    "Decline Barbell Bench Press": "https://www.youtube.com/watch?v=LfyQBUKR8SE",
    "Pec Deck Machine": "https://www.youtube.com/shorts/l6_jBvwzPzg",
    "Seated Leg Press": "https://www.youtube.com/watch?v=8EMbB0tCn7Q",
    "Glute Bridge": "https://www.youtube.com/watch?v=OUgsJ8-Vi0E",
    "Hip Thrust": "https://www.youtube.com/shorts/W86oVlnLqY4",
    "Stair Climber": "https://www.youtube.com/shorts/6mYp_BNYD5Y",
    "Treadmill Running": None,
    "Ab Wheel Rollout": "https://www.youtube.com/watch?v=9ZCoAbI7uX0",
    "Cable Crossover": "https://www.youtube.com/watch?v=taI4XduLpTk",
    "Seated Cable Row": "https://www.youtube.com/watch?v=vwHG9Jfu4sw",
    "Cable Curl": "https://www.youtube.com/watch?v=NFzTWp2qpiE",
    "Cable Tricep Pushdown": "https://www.youtube.com/watch?v=-zLyUAo1gMw",
    "Glute Kickback": "https://www.youtube.com/shorts/fuV-vkCZC0A",
    "Cable Crunch": "https://www.youtube.com/shorts/M1HeORCwv8A",
    "Cable Lateral Raise": "https://www.youtube.com/watch?v=PPrzBWZDOhA",
    "Dumbbell Pullover": "https://www.youtube.com/watch?v=FK4rHfWKEac",
    "Hyperextension (Back Extension)": "https://www.youtube.com/watch?v=H8Swl1N-uis",
    "Seated Dumbell Rear Delt Raise": "https://www.youtube.com/watch?v=p1yQnTNE808"

}
